### ISSUE TITLE
test_b306 in test_sentry_check.py fails on Python 3

### ISSUE THREAD

**Issue by cclauss** [getsentry/sentry-flake8#6]
See #5 output https://travis-ci.com/getsentry/sentry-flake8/jobs/247390137#L222

Blocks getsentry/sentry#14906

@joshuarli

**Comment by joshuarli** [comment]
That failure is on 3.8, we're going to try to stick to targetting 3.7 first (or maybe even 3.6 if some dependencies aren't 2.x and 3.7 compat) during the py3 upgrade.

**Comment by joshuarli** [comment]
Oh never mind, it manifests on both 3.7 and 3.8. Anyways, it seems to be fixed in https://github.com/getsentry/sentry-flake8/pull/5/commits/a953d4dbb2b1c4a70fd30c22f07a2bd41a24618d#diff-5c4964327f40cb816785447336f25538R117.
